//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekasnSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Application
    {
        public int ID_Application { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        
        [StringLength(20, MinimumLength = 7)]
        public string Status { get; set; }
        public Nullable<int> ResponsibleTeacherID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public object Applications { get; internal set; }
    }
}
